//! Integration tests for the async export-job path (item 6 of the export epic,
//! ADR-0003): `POST .../entities/export` with `async: true` and the
//! `GET .../exports/{job_id}` status endpoint.
//!
//! In-process SurrealDB (`mem://`); storage is mocked with an in-memory
//! [`MockStore`] — no live MinIO/S3. The full lifecycle test drives the
//! [`ExportJobActor`] directly with a mock store so the generated bytes and the
//! `queued -> running -> complete` transitions are observable without a real
//! object store; the HTTP tests cover the 202-queued accept, the no-storage
//! refusal, and the schema-scoped status gate.

use std::collections::HashMap;
use std::sync::Arc;
use std::time::Duration;

use acton_service::config::Config;
use acton_service::middleware::Claims;
use acton_service::prelude::{ActorHandle, ActorHandleInterface};
use acton_service::state::AppState;
use async_trait::async_trait;
use axum::body::Body;
use axum::http::{Method, Request, StatusCode};
use axum::Router;
use http_body_util::BodyExt;
use std::sync::Mutex;

use schema_forge_acton::config::SchemaForgeConfig;
use schema_forge_acton::export_job::{
    ExportJobActor, ExportJobSpec, ExportJobStatus, GetExportJob, StartExportJob,
};
use schema_forge_acton::messages::{
    GetPolicyStore, GetRecordAccessPolicy, GetTenantConfig, InitForge, ReplyChannel,
};
use schema_forge_acton::routes::forge_routes;
use schema_forge_acton::state::DynForgeBackend;
use schema_forge_acton::storage::{ExportArtifactStore, StorageError};
use schema_forge_acton::DynSchemaBackend;
use schema_forge_acton::ForgeActor;
use schema_forge_core::types::{
    Annotation, ExportFormat, FieldAnnotation, FieldDefinition, FieldName, FieldType,
    SchemaDefinition, SchemaId, SchemaName, TextConstraints,
};
use schema_forge_surrealdb::SurrealBackend;
use tokio::sync::oneshot;
use tower::ServiceExt;

// ---------------------------------------------------------------------------
// Mock storage
// ---------------------------------------------------------------------------

/// In-memory [`ExportArtifactStore`] capturing every uploaded object so a test
/// can assert on the generated bytes and content type without any live S3.
#[derive(Debug, Default)]
struct MockStore {
    objects: Mutex<HashMap<String, (Vec<u8>, String)>>,
}

#[async_trait]
impl ExportArtifactStore for MockStore {
    async fn put(
        &self,
        key: &str,
        bytes: Vec<u8>,
        content_type: &str,
    ) -> Result<(), StorageError> {
        self.objects
            .lock()
            .unwrap()
            .insert(key.to_string(), (bytes, content_type.to_string()));
        Ok(())
    }

    async fn presign_get(
        &self,
        key: &str,
        _ttl_secs: Option<u64>,
    ) -> Result<String, StorageError> {
        if self.objects.lock().unwrap().contains_key(key) {
            Ok(format!("https://mock.example/{key}?sig=abc"))
        } else {
            Err(StorageError::Request("object not found".into()))
        }
    }
}

// ---------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------

fn make_claims(roles: &[&str]) -> Claims {
    Claims {
        sub: "user:test-user".to_string(),
        roles: roles.iter().map(|r| r.to_string()).collect(),
        perms: vec![],
        exp: 9_999_999_999,
        iat: None,
        jti: None,
        iss: None,
        aud: None,
        email: None,
        username: None,
        custom: HashMap::new(),
    }
}

async fn build_state(
    backend: Arc<dyn DynForgeBackend>,
    registry: HashMap<String, SchemaDefinition>,
) -> AppState<SchemaForgeConfig> {
    use acton_service::service_builder::ServiceBuilder;

    let config = Config::<SchemaForgeConfig>::default();
    let service = ServiceBuilder::new()
        .with_config(config)
        .with_actor::<ForgeActor>()
        .with_actor::<schema_forge_acton::HookDispatchActor>()
        .with_actor::<ExportJobActor>()
        .build();

    let forge_handle = service
        .state()
        .actor::<ForgeActor>()
        .expect("ForgeActor not registered");

    let (tx, rx) = oneshot::channel();
    forge_handle
        .send(InitForge {
            registry,
            backend,
            tenant_config: None,
            record_access_policy: None,
            hook_dispatcher: None,
            storage_registry: schema_forge_acton::storage::StorageRegistry::default(),
            policy_store: None,
            custom_policies_dir: None,
            reply: ReplyChannel::new(tx),
        })
        .await;
    tokio::time::timeout(Duration::from_secs(5), rx)
        .await
        .expect("InitForge timeout")
        .expect("InitForge channel dropped");

    service.state().clone()
}

fn app_with_claims(state: AppState<SchemaForgeConfig>, claims: Claims) -> Router {
    forge_routes()
        .layer(axum::middleware::from_fn(
            move |mut req: axum::extract::Request, next: axum::middleware::Next| {
                let claims = claims.clone();
                async move {
                    req.extensions_mut().insert(claims);
                    next.run(req).await
                }
            },
        ))
        .with_state(state)
}

async fn raw_request(
    app: &Router,
    method: Method,
    path: &str,
    body: Option<serde_json::Value>,
) -> (StatusCode, serde_json::Value) {
    let body = match body {
        Some(v) => Body::from(serde_json::to_vec(&v).unwrap()),
        None => Body::empty(),
    };
    let request = Request::builder()
        .method(method)
        .uri(path)
        .header("content-type", "application/json")
        .body(body)
        .unwrap();
    let response = app.clone().oneshot(request).await.unwrap();
    let status = response.status();
    let bytes = response.into_body().collect().await.unwrap().to_bytes();
    let json = if bytes.is_empty() {
        serde_json::Value::Null
    } else {
        serde_json::from_slice(&bytes).unwrap_or(serde_json::Value::Null)
    };
    (status, json)
}

fn exportable_field(name: &str) -> FieldDefinition {
    FieldDefinition::with_annotations(
        FieldName::new(name).unwrap(),
        FieldType::Text(TextConstraints::unconstrained()),
        vec![],
        vec![FieldAnnotation::Exportable { flatten: None }],
    )
}

fn plain_field(name: &str) -> FieldDefinition {
    FieldDefinition::new(
        FieldName::new(name).unwrap(),
        FieldType::Text(TextConstraints::unconstrained()),
    )
}

/// `Subject`: `name` + `notes` exportable, `secret` readable-but-not-exportable.
fn export_schema() -> SchemaDefinition {
    SchemaDefinition::new(
        SchemaId::new(),
        SchemaName::new("Subject").unwrap(),
        vec![
            exportable_field("name"),
            exportable_field("notes"),
            plain_field("secret"),
        ],
        vec![
            Annotation::Access {
                read: vec!["analyst".to_string()],
                write: vec!["analyst".to_string()],
                delete: vec![],
                cross_tenant_read: vec![],
            },
            Annotation::Export {
                formats: vec![ExportFormat::Csv, ExportFormat::Ndjson],
                bundle_files: false,
                max_rows: 100,
            },
        ],
    )
    .unwrap()
}

async fn provision(backend: &Arc<SurrealBackend>, schema: &SchemaDefinition) {
    let plan = schema_forge_core::migration::DiffEngine::create_new(schema);
    backend
        .apply_migration(&schema.name, &plan.steps)
        .await
        .expect("migration");
    backend
        .store_schema_metadata(schema)
        .await
        .expect("metadata");
}

/// Build state + a seeded `Subject` table; returns the state and the seeding
/// admin app so callers can drive both the actor directly and the HTTP routes.
async fn seeded_state(
    schema: SchemaDefinition,
    rows: &[serde_json::Value],
) -> AppState<SchemaForgeConfig> {
    let backend = Arc::new(
        SurrealBackend::connect_memory("test", "test")
            .await
            .expect("mem surreal"),
    );
    provision(&backend, &schema).await;

    let mut registry = HashMap::new();
    registry.insert(schema.name.as_str().to_string(), schema.clone());
    let state = build_state(backend, registry).await;

    let admin = app_with_claims(state.clone(), make_claims(&["platform_admin"]));
    let path = format!("/schemas/{}/entities", schema.name.as_str());
    for row in rows {
        let (status, json) = raw_request(&admin, Method::POST, &path, Some(row.clone())).await;
        assert_eq!(status, StatusCode::CREATED, "seed failed: {json}");
    }
    state
}

/// Pull the inputs `materialize_export` needs out of the live actor so a test can
/// assemble an `ExportJobSpec` exactly as the route handler would.
async fn job_inputs(
    state: &AppState<SchemaForgeConfig>,
    schema: &str,
) -> (
    ActorHandle,
    SchemaDefinition,
    Arc<schema_forge_acton::authz::PolicyStore>,
    Option<schema_forge_backend::tenant::TenantConfig>,
    Option<Arc<dyn schema_forge_backend::auth::RecordAccessPolicy>>,
) {
    let forge = state.actor::<ForgeActor>().expect("ForgeActor").clone();

    let (tx, rx) = oneshot::channel();
    forge
        .send(schema_forge_acton::messages::GetSchema {
            name: schema.to_string(),
            reply: ReplyChannel::new(tx),
        })
        .await;
    let schema_def = rx.await.unwrap().expect("schema registered");

    let (tx, rx) = oneshot::channel();
    forge.send(GetPolicyStore { reply: ReplyChannel::new(tx) }).await;
    let policy_store = rx.await.unwrap().expect("policy store");

    let (tx, rx) = oneshot::channel();
    forge.send(GetTenantConfig { reply: ReplyChannel::new(tx) }).await;
    let tenant_config = rx.await.unwrap();

    let (tx, rx) = oneshot::channel();
    forge
        .send(GetRecordAccessPolicy { reply: ReplyChannel::new(tx) })
        .await;
    let record_access_policy = rx.await.unwrap();

    (forge, schema_def, policy_store, tenant_config, record_access_policy)
}

async fn poll_until_terminal(
    job_actor: &ActorHandle,
    job_id: &str,
) -> schema_forge_acton::export_job::ExportJobRecord {
    for _ in 0..200 {
        let (tx, rx) = oneshot::channel();
        job_actor
            .send(GetExportJob {
                job_id: job_id.to_string(),
                reply: ReplyChannel::new(tx),
            })
            .await;
        if let Some(record) = rx.await.unwrap() {
            if matches!(
                record.status,
                ExportJobStatus::Complete | ExportJobStatus::Failed
            ) {
                return record;
            }
        }
        tokio::time::sleep(Duration::from_millis(10)).await;
    }
    panic!("export job did not reach a terminal state in time");
}

// ---------------------------------------------------------------------------
// Tests — actor lifecycle with mock storage
// ---------------------------------------------------------------------------

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn async_job_generates_csv_and_uploads_to_store() {
    let rows = [
        serde_json::json!({ "fields": { "name": "Ada", "notes": "vip", "secret": "SSN-111" } }),
        serde_json::json!({ "fields": { "name": "Bob", "notes": "x,y", "secret": "SSN-222" } }),
    ];
    let state = seeded_state(export_schema(), &rows).await;
    let (forge, schema_def, policy_store, tenant_config, record_access_policy) =
        job_inputs(&state, "Subject").await;
    let job_actor = state.actor::<ExportJobActor>().expect("ExportJobActor").clone();

    let store = Arc::new(MockStore::default());
    let job_id = schema_forge_acton::export_job::new_job_id();
    let object_key = format!("exports/Subject/{job_id}.csv");

    let spec = ExportJobSpec {
        job_id: job_id.clone(),
        schema_name: "Subject".into(),
        schema_def,
        format: ExportFormat::Csv,
        filter: None,
        fields: None,
        max_rows: 100,
        claims: Some(make_claims(&["platform_admin"])),
        tenant_config,
        policy_store,
        record_access_policy,
        forge,
        store: store.clone(),
        object_key: object_key.clone(),
        audit_logger: None,
        subject: Some("user:test-user".into()),
    };

    job_actor.send(StartExportJob::new(spec)).await;
    let record = poll_until_terminal(&job_actor, &job_id).await;

    assert_eq!(record.status, ExportJobStatus::Complete, "error: {:?}", record.error);
    assert_eq!(record.row_count, Some(2));
    assert_eq!(record.object_key.as_deref(), Some(object_key.as_str()));

    // The mock store received the exact CSV bytes, exportable columns only.
    // Scope the lock so it is released before `to_status_json` (which re-locks
    // the store to mint the presigned url) is awaited below.
    {
        let objects = store.objects.lock().unwrap();
        let (bytes, ctype) = objects.get(&object_key).expect("artifact uploaded");
        assert!(ctype.starts_with("text/csv"));
        let text = String::from_utf8(bytes.clone()).unwrap();
        assert_eq!(text.lines().next().unwrap(), "name,notes");
        assert!(!text.contains("SSN-111"), "leaked secret: {text}");
        assert!(text.contains("\"x,y\""), "csv quoting wrong: {text}");
    }

    // The status JSON for a complete job carries a presigned download url.
    let status = record.to_status_json().await;
    assert_eq!(status["status"], "complete");
    assert_eq!(status["row_count"], 2);
    assert!(status["download_url"]
        .as_str()
        .unwrap()
        .contains(&object_key));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn async_job_over_cap_fails_without_uploading() {
    // Cap of 1, two rows: the materialize pipeline returns ExportTooLarge, which
    // the actor records as a failed job — and nothing is written to storage.
    let mut schema = export_schema();
    schema.annotations.retain(|a| !matches!(a, Annotation::Export { .. }));
    schema.annotations.push(Annotation::Export {
        formats: vec![ExportFormat::Csv, ExportFormat::Ndjson],
        bundle_files: false,
        max_rows: 1,
    });

    let rows = [
        serde_json::json!({ "fields": { "name": "Ada", "notes": "a" } }),
        serde_json::json!({ "fields": { "name": "Bob", "notes": "b" } }),
    ];
    let state = seeded_state(schema, &rows).await;
    let (forge, schema_def, policy_store, tenant_config, record_access_policy) =
        job_inputs(&state, "Subject").await;
    let job_actor = state.actor::<ExportJobActor>().expect("ExportJobActor").clone();

    let store = Arc::new(MockStore::default());
    let job_id = schema_forge_acton::export_job::new_job_id();
    let object_key = format!("exports/Subject/{job_id}.csv");
    let spec = ExportJobSpec {
        job_id: job_id.clone(),
        schema_name: "Subject".into(),
        schema_def,
        format: ExportFormat::Csv,
        filter: None,
        fields: None,
        max_rows: 1,
        claims: Some(make_claims(&["platform_admin"])),
        tenant_config,
        policy_store,
        record_access_policy,
        forge,
        store: store.clone(),
        object_key: object_key.clone(),
        audit_logger: None,
        subject: None,
    };

    job_actor.send(StartExportJob::new(spec)).await;
    let record = poll_until_terminal(&job_actor, &job_id).await;

    assert_eq!(record.status, ExportJobStatus::Failed);
    assert!(record.error.unwrap().contains("cap"));
    assert!(store.objects.lock().unwrap().is_empty(), "failed job must not upload");
}

// ---------------------------------------------------------------------------
// Tests — HTTP surface
// ---------------------------------------------------------------------------

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn async_request_without_storage_is_unavailable() {
    // No storage backend is configured in the test harness, so an async export
    // has nowhere to land and is refused with 503 rather than accepted.
    let rows = [serde_json::json!({ "fields": { "name": "Ada", "notes": "n" } })];
    let state = seeded_state(export_schema(), &rows).await;
    let app = app_with_claims(state, make_claims(&["platform_admin"]));

    let (status, json) = raw_request(
        &app,
        Method::POST,
        "/schemas/Subject/entities/export",
        Some(serde_json::json!({ "format": "csv", "async": true })),
    )
    .await;

    assert_eq!(status, StatusCode::SERVICE_UNAVAILABLE, "body: {json}");
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn status_for_unknown_job_is_not_found() {
    let rows = [serde_json::json!({ "fields": { "name": "Ada", "notes": "n" } })];
    let state = seeded_state(export_schema(), &rows).await;
    let app = app_with_claims(state, make_claims(&["platform_admin"]));

    let (status, json) = raw_request(
        &app,
        Method::GET,
        "/schemas/Subject/exports/exp_does_not_exist",
        None,
    )
    .await;

    assert_eq!(status, StatusCode::NOT_FOUND, "body: {json}");
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn status_on_non_export_schema_is_forbidden() {
    // A schema with no @export must refuse status lookups, fail-closed, even
    // though the job id is unknown — the export gate runs before the lookup.
    let schema = SchemaDefinition::new(
        SchemaId::new(),
        SchemaName::new("Locked").unwrap(),
        vec![exportable_field("name")],
        vec![Annotation::Access {
            read: vec!["analyst".to_string()],
            write: vec!["analyst".to_string()],
            delete: vec![],
            cross_tenant_read: vec![],
        }],
    )
    .unwrap();
    let state = seeded_state(schema, &[]).await;
    let app = app_with_claims(state, make_claims(&["platform_admin"]));

    let (status, json) = raw_request(
        &app,
        Method::GET,
        "/schemas/Locked/exports/exp_anything",
        None,
    )
    .await;

    assert_eq!(status, StatusCode::FORBIDDEN, "body: {json}");
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn status_endpoint_returns_completed_job_with_download_url() {
    // Drive a job to completion through the actor with a mock store, register it
    // under a known id, then read it back through the HTTP status route.
    let rows = [serde_json::json!({ "fields": { "name": "Ada", "notes": "n" } })];
    let state = seeded_state(export_schema(), &rows).await;
    let (forge, schema_def, policy_store, tenant_config, record_access_policy) =
        job_inputs(&state, "Subject").await;
    let job_actor = state.actor::<ExportJobActor>().expect("ExportJobActor").clone();

    let store = Arc::new(MockStore::default());
    let job_id = schema_forge_acton::export_job::new_job_id();
    let object_key = format!("exports/Subject/{job_id}.ndjson");
    let spec = ExportJobSpec {
        job_id: job_id.clone(),
        schema_name: "Subject".into(),
        schema_def,
        format: ExportFormat::Ndjson,
        filter: None,
        fields: None,
        max_rows: 100,
        claims: Some(make_claims(&["platform_admin"])),
        tenant_config,
        policy_store,
        record_access_policy,
        forge,
        store,
        object_key,
        audit_logger: None,
        subject: None,
    };
    job_actor.send(StartExportJob::new(spec)).await;
    let record = poll_until_terminal(&job_actor, &job_id).await;
    assert_eq!(record.status, ExportJobStatus::Complete);

    let app = app_with_claims(state, make_claims(&["platform_admin"]));
    let (status, json) = raw_request(
        &app,
        Method::GET,
        &format!("/schemas/Subject/exports/{job_id}"),
        None,
    )
    .await;

    assert_eq!(status, StatusCode::OK, "body: {json}");
    assert_eq!(json["status"], "complete");
    assert_eq!(json["job_id"], job_id);
    assert!(json["download_url"].as_str().unwrap().starts_with("https://mock.example/"));
}
