//! Integration tests for the async export-job path (item 6 of the export epic,
//! ADR-0003): `POST .../entities/export` with `async: true` and the
//! `GET .../exports/{job_id}` status endpoint.
//!
//! In-process SurrealDB (`mem://`); storage is mocked with an in-memory
//! [`MockStore`] — no live MinIO/S3. The full lifecycle test drives the
//! [`ExportJobActor`] directly with a mock store so the generated bytes and the
//! `queued -> running -> complete` transitions are observable without a real
//! object store; the HTTP tests cover the 202-queued accept, the no-storage
//! refusal, and the schema-scoped status gate.

use std::collections::HashMap;
use std::sync::Arc;
use std::time::Duration;

use acton_service::config::Config;
use acton_service::middleware::Claims;
use acton_service::prelude::{ActorHandle, ActorHandleInterface};
use acton_service::state::AppState;
use async_trait::async_trait;
use axum::body::Body;
use axum::http::{Method, Request, StatusCode};
use axum::Router;
use http_body_util::BodyExt;
use std::sync::Mutex;

use schema_forge_acton::config::SchemaForgeConfig;
use schema_forge_acton::export_job::{
    ExportJobActor, ExportJobSpec, ExportJobStatus, GetExportJob, StartExportJob,
};
use schema_forge_acton::messages::{
    GetPolicyStore, GetRecordAccessPolicy, GetTenantConfig, InitForge, ReplyChannel,
};
use schema_forge_acton::routes::forge_routes;
use schema_forge_acton::state::DynForgeBackend;
use schema_forge_acton::storage::{ExportArtifactStore, StorageError};
use schema_forge_acton::DynSchemaBackend;
use schema_forge_acton::ForgeActor;
use schema_forge_core::types::{
    Annotation, ExportFormat, FieldAnnotation, FieldDefinition, FieldName, FieldType,
    SchemaDefinition, SchemaId, SchemaName, TextConstraints,
};
use schema_forge_surrealdb::SurrealBackend;
use tokio::sync::oneshot;
use tower::ServiceExt;

// ---------------------------------------------------------------------------
// Mock storage
// ---------------------------------------------------------------------------

/// In-memory [`ExportArtifactStore`] capturing every uploaded object so a test
/// can assert on the generated bytes and content type without any live S3.
#[derive(Debug, Default)]
struct MockStore {
    objects: Mutex<HashMap<String, (Vec<u8>, String)>>,
}

#[async_trait]
impl ExportArtifactStore for MockStore {
    async fn put(
        &self,
        key: &str,
        bytes: Vec<u8>,
        content_type: &str,
    ) -> Result<(), StorageError> {
        self.objects
            .lock()
            .unwrap()
            .insert(key.to_string(), (bytes, content_type.to_string()));
        Ok(())
    }

    async fn presign_get(
        &self,
        key: &str,
        _ttl_secs: Option<u64>,
    ) -> Result<String, StorageError> {
        if self.objects.lock().unwrap().contains_key(key) {
            Ok(format!("https://mock.example/{key}?sig=abc"))
        } else {
            Err(StorageError::Request("object not found".into()))
        }
    }

    async fn get(&self, key: &str) -> Result<Vec<u8>, StorageError> {
        self.objects
            .lock()
            .unwrap()
            .get(key)
            .map(|(bytes, _)| bytes.clone())
            .ok_or_else(|| StorageError::Request(format!("object '{key}' not found")))
    }
}

impl MockStore {
    /// Seed a raw object (e.g. a `file`-field blob) so the ZIP bundle path can
    /// pull it back out via [`ExportArtifactStore::get`].
    fn seed_object(&self, key: &str, bytes: Vec<u8>, content_type: &str) {
        self.objects
            .lock()
            .unwrap()
            .insert(key.to_string(), (bytes, content_type.to_string()));
    }
}

// ---------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------

fn make_claims(roles: &[&str]) -> Claims {
    Claims {
        sub: "user:test-user".to_string(),
        roles: roles.iter().map(|r| r.to_string()).collect(),
        perms: vec![],
        exp: 9_999_999_999,
        iat: None,
        jti: None,
        iss: None,
        aud: None,
        email: None,
        username: None,
        custom: HashMap::new(),
    }
}

/// Claims for a specific subject, same shape as [`make_claims`] otherwise.
fn make_claims_with_sub(sub: &str, roles: &[&str]) -> Claims {
    Claims {
        sub: sub.to_string(),
        ..make_claims(roles)
    }
}

async fn build_state(
    backend: Arc<dyn DynForgeBackend>,
    registry: HashMap<String, SchemaDefinition>,
) -> AppState<SchemaForgeConfig> {
    use acton_service::service_builder::ServiceBuilder;

    let config = Config::<SchemaForgeConfig>::default();
    let service = ServiceBuilder::new()
        .with_config(config)
        .with_actor::<ForgeActor>()
        .with_actor::<schema_forge_acton::HookDispatchActor>()
        .with_actor::<ExportJobActor>()
        .with_actor::<schema_forge_acton::ExportRateLimiter>()
        .build();

    let forge_handle = service
        .state()
        .actor::<ForgeActor>()
        .expect("ForgeActor not registered");

    let (tx, rx) = oneshot::channel();
    forge_handle
        .send(InitForge {
            registry,
            backend,
            tenant_config: None,
            record_access_policy: None,
            hook_dispatcher: None,
            storage_registry: schema_forge_acton::storage::StorageRegistry::default(),
            policy_store: None,
            custom_policies_dir: None,
            reply: ReplyChannel::new(tx),
        })
        .await;
    tokio::time::timeout(Duration::from_secs(5), rx)
        .await
        .expect("InitForge timeout")
        .expect("InitForge channel dropped");

    service.state().clone()
}

fn app_with_claims(state: AppState<SchemaForgeConfig>, claims: Claims) -> Router {
    forge_routes()
        .layer(axum::middleware::from_fn(
            move |mut req: axum::extract::Request, next: axum::middleware::Next| {
                let claims = claims.clone();
                async move {
                    req.extensions_mut().insert(claims);
                    next.run(req).await
                }
            },
        ))
        .with_state(state)
}

async fn raw_request(
    app: &Router,
    method: Method,
    path: &str,
    body: Option<serde_json::Value>,
) -> (StatusCode, serde_json::Value) {
    let body = match body {
        Some(v) => Body::from(serde_json::to_vec(&v).unwrap()),
        None => Body::empty(),
    };
    let request = Request::builder()
        .method(method)
        .uri(path)
        .header("content-type", "application/json")
        .body(body)
        .unwrap();
    let response = app.clone().oneshot(request).await.unwrap();
    let status = response.status();
    let bytes = response.into_body().collect().await.unwrap().to_bytes();
    let json = if bytes.is_empty() {
        serde_json::Value::Null
    } else {
        serde_json::from_slice(&bytes).unwrap_or(serde_json::Value::Null)
    };
    (status, json)
}

fn exportable_field(name: &str) -> FieldDefinition {
    FieldDefinition::with_annotations(
        FieldName::new(name).unwrap(),
        FieldType::Text(TextConstraints::unconstrained()),
        vec![],
        vec![FieldAnnotation::Exportable { flatten: None }],
    )
}

fn plain_field(name: &str) -> FieldDefinition {
    FieldDefinition::new(
        FieldName::new(name).unwrap(),
        FieldType::Text(TextConstraints::unconstrained()),
    )
}

/// `Subject`: `name` + `notes` exportable, `secret` readable-but-not-exportable.
fn export_schema() -> SchemaDefinition {
    SchemaDefinition::new(
        SchemaId::new(),
        SchemaName::new("Subject").unwrap(),
        vec![
            exportable_field("name"),
            exportable_field("notes"),
            plain_field("secret"),
        ],
        vec![
            Annotation::Access {
                read: vec!["analyst".to_string()],
                write: vec!["analyst".to_string()],
                delete: vec![],
                cross_tenant_read: vec![],
            },
            Annotation::Export {
                formats: vec![ExportFormat::Csv, ExportFormat::Ndjson],
                bundle_files: false,
                max_rows: 100,
            },
        ],
    )
    .unwrap()
}

async fn provision(backend: &Arc<SurrealBackend>, schema: &SchemaDefinition) {
    let plan = schema_forge_core::migration::DiffEngine::create_new(schema);
    backend
        .apply_migration(&schema.name, &plan.steps)
        .await
        .expect("migration");
    backend
        .store_schema_metadata(schema)
        .await
        .expect("metadata");
}

/// Build state + a seeded `Subject` table; returns the state and the seeding
/// admin app so callers can drive both the actor directly and the HTTP routes.
async fn seeded_state(
    schema: SchemaDefinition,
    rows: &[serde_json::Value],
) -> AppState<SchemaForgeConfig> {
    let backend = Arc::new(
        SurrealBackend::connect_memory("test", "test")
            .await
            .expect("mem surreal"),
    );
    provision(&backend, &schema).await;

    let mut registry = HashMap::new();
    registry.insert(schema.name.as_str().to_string(), schema.clone());
    let state = build_state(backend, registry).await;

    let admin = app_with_claims(state.clone(), make_claims(&["platform_admin"]));
    let path = format!("/schemas/{}/entities", schema.name.as_str());
    for row in rows {
        let (status, json) = raw_request(&admin, Method::POST, &path, Some(row.clone())).await;
        assert_eq!(status, StatusCode::CREATED, "seed failed: {json}");
    }
    state
}

/// Pull the inputs `materialize_export` needs out of the live actor so a test can
/// assemble an `ExportJobSpec` exactly as the route handler would.
async fn job_inputs(
    state: &AppState<SchemaForgeConfig>,
    schema: &str,
) -> (
    ActorHandle,
    SchemaDefinition,
    Arc<schema_forge_acton::authz::PolicyStore>,
    Option<schema_forge_backend::tenant::TenantConfig>,
    Option<Arc<dyn schema_forge_backend::auth::RecordAccessPolicy>>,
) {
    let forge = state.actor::<ForgeActor>().expect("ForgeActor").clone();

    let (tx, rx) = oneshot::channel();
    forge
        .send(schema_forge_acton::messages::GetSchema {
            name: schema.to_string(),
            reply: ReplyChannel::new(tx),
        })
        .await;
    let schema_def = rx.await.unwrap().expect("schema registered");

    let (tx, rx) = oneshot::channel();
    forge.send(GetPolicyStore { reply: ReplyChannel::new(tx) }).await;
    let policy_store = rx.await.unwrap().expect("policy store");

    let (tx, rx) = oneshot::channel();
    forge.send(GetTenantConfig { reply: ReplyChannel::new(tx) }).await;
    let tenant_config = rx.await.unwrap();

    let (tx, rx) = oneshot::channel();
    forge
        .send(GetRecordAccessPolicy { reply: ReplyChannel::new(tx) })
        .await;
    let record_access_policy = rx.await.unwrap();

    (forge, schema_def, policy_store, tenant_config, record_access_policy)
}

async fn poll_until_terminal(
    job_actor: &ActorHandle,
    job_id: &str,
) -> schema_forge_acton::export_job::ExportJobRecord {
    for _ in 0..200 {
        let (tx, rx) = oneshot::channel();
        job_actor
            .send(GetExportJob {
                job_id: job_id.to_string(),
                reply: ReplyChannel::new(tx),
            })
            .await;
        if let Some(record) = rx.await.unwrap() {
            if matches!(
                record.status,
                ExportJobStatus::Complete | ExportJobStatus::Failed
            ) {
                return record;
            }
        }
        tokio::time::sleep(Duration::from_millis(10)).await;
    }
    panic!("export job did not reach a terminal state in time");
}

// ---------------------------------------------------------------------------
// Tests — actor lifecycle with mock storage
// ---------------------------------------------------------------------------

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn async_job_generates_csv_and_uploads_to_store() {
    let rows = [
        serde_json::json!({ "fields": { "name": "Ada", "notes": "vip", "secret": "SSN-111" } }),
        serde_json::json!({ "fields": { "name": "Bob", "notes": "x,y", "secret": "SSN-222" } }),
    ];
    let state = seeded_state(export_schema(), &rows).await;
    let (forge, schema_def, policy_store, tenant_config, record_access_policy) =
        job_inputs(&state, "Subject").await;
    let job_actor = state.actor::<ExportJobActor>().expect("ExportJobActor").clone();

    let store = Arc::new(MockStore::default());
    let job_id = schema_forge_acton::export_job::new_job_id();
    let object_key = format!("exports/Subject/{job_id}.csv");

    let spec = ExportJobSpec {
        job_id: job_id.clone(),
        schema_name: "Subject".into(),
        schema_def,
        format: ExportFormat::Csv,
        filter: None,
        fields: None,
        max_rows: 100,
        bundle_files: false,
        claims: Some(make_claims(&["platform_admin"])),
        tenant_config,
        policy_store,
        record_access_policy,
        forge,
        store: store.clone(),
        object_key: object_key.clone(),
        audit_logger: None,
        subject: Some("user:test-user".into()),
    };

    job_actor.send(StartExportJob::new(spec)).await;
    let record = poll_until_terminal(&job_actor, &job_id).await;

    assert_eq!(record.status, ExportJobStatus::Complete, "error: {:?}", record.error);
    assert_eq!(record.row_count, Some(2));
    assert_eq!(record.object_key.as_deref(), Some(object_key.as_str()));

    // The mock store received the exact CSV bytes, exportable columns only.
    // Scope the lock so it is released before `to_status_json` (which re-locks
    // the store to mint the presigned url) is awaited below.
    {
        let objects = store.objects.lock().unwrap();
        let (bytes, ctype) = objects.get(&object_key).expect("artifact uploaded");
        assert!(ctype.starts_with("text/csv"));
        let text = String::from_utf8(bytes.clone()).unwrap();
        assert_eq!(text.lines().next().unwrap(), "name,notes");
        assert!(!text.contains("SSN-111"), "leaked secret: {text}");
        assert!(text.contains("\"x,y\""), "csv quoting wrong: {text}");
    }

    // The status JSON for a complete job carries a presigned download url.
    let status = record.to_status_json().await;
    assert_eq!(status["status"], "complete");
    assert_eq!(status["row_count"], 2);
    assert!(status["download_url"]
        .as_str()
        .unwrap()
        .contains(&object_key));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn async_job_generates_xlsx_and_uploads_well_formed_workbook() {
    // XLSX is async-only (rust_xlsxwriter buffers the whole workbook). Drive the
    // job actor with a mock store, then read the uploaded bytes back with
    // calamine to confirm a well-formed workbook with the exportable columns and
    // no leak of the readable-but-not-exportable `secret` field.
    use calamine::{Data, Reader, Xlsx};
    use std::io::Cursor;

    let rows = [
        serde_json::json!({ "fields": { "name": "Ada", "notes": "vip", "secret": "SSN-111" } }),
        serde_json::json!({ "fields": { "name": "Bob", "notes": "x,y", "secret": "SSN-222" } }),
    ];
    let state = seeded_state(export_schema(), &rows).await;
    let (forge, schema_def, policy_store, tenant_config, record_access_policy) =
        job_inputs(&state, "Subject").await;
    let job_actor = state.actor::<ExportJobActor>().expect("ExportJobActor").clone();

    let store = Arc::new(MockStore::default());
    let job_id = schema_forge_acton::export_job::new_job_id();
    let object_key = format!("exports/Subject/{job_id}.xlsx");

    let spec = ExportJobSpec {
        job_id: job_id.clone(),
        schema_name: "Subject".into(),
        schema_def,
        format: ExportFormat::Xlsx,
        filter: None,
        fields: None,
        max_rows: 100,
        bundle_files: false,
        claims: Some(make_claims(&["platform_admin"])),
        tenant_config,
        policy_store,
        record_access_policy,
        forge,
        store: store.clone(),
        object_key: object_key.clone(),
        audit_logger: None,
        subject: Some("user:test-user".into()),
    };

    job_actor.send(StartExportJob::new(spec)).await;
    let record = poll_until_terminal(&job_actor, &job_id).await;

    assert_eq!(
        record.status,
        ExportJobStatus::Complete,
        "error: {:?}",
        record.error
    );
    assert_eq!(record.row_count, Some(2));

    // Pull the uploaded artifact out of the mock store and parse it back.
    let bytes = {
        let objects = store.objects.lock().unwrap();
        let (bytes, ctype) = objects.get(&object_key).expect("artifact uploaded");
        assert!(
            ctype.contains("spreadsheetml.sheet"),
            "wrong content type: {ctype}"
        );
        // A valid xlsx is a ZIP container starting with the PK signature.
        assert_eq!(&bytes[..2], b"PK", "not a zip/xlsx container");
        bytes.clone()
    };

    let mut wb: Xlsx<_> =
        calamine::open_workbook_from_rs(Cursor::new(bytes)).expect("valid xlsx workbook");
    let sheet = wb.sheet_names()[0].clone();
    let range = wb.worksheet_range(&sheet).expect("first sheet");

    // Header row: exportable columns only (`secret` is excluded).
    let header: Vec<String> = range
        .rows()
        .next()
        .unwrap()
        .iter()
        .map(|c| c.to_string())
        .collect();
    assert_eq!(header, vec!["name", "notes"]);

    // Two data rows landed, with the expected values.
    assert_eq!(range.height(), 3, "header + 2 data rows");
    assert_eq!(range.get_value((1, 0)), Some(&Data::String("Ada".into())));
    assert_eq!(range.get_value((2, 1)), Some(&Data::String("x,y".into())));

    // The readable-but-not-exportable secret must never appear in any cell.
    let any_secret = range
        .rows()
        .flat_map(|r| r.iter())
        .any(|c| c.to_string().contains("SSN-"));
    assert!(!any_secret, "xlsx leaked the secret field");
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn async_job_over_cap_fails_without_uploading() {
    // Cap of 1, two rows: the materialize pipeline returns ExportTooLarge, which
    // the actor records as a failed job — and nothing is written to storage.
    let mut schema = export_schema();
    schema.annotations.retain(|a| !matches!(a, Annotation::Export { .. }));
    schema.annotations.push(Annotation::Export {
        formats: vec![ExportFormat::Csv, ExportFormat::Ndjson],
        bundle_files: false,
        max_rows: 1,
    });

    let rows = [
        serde_json::json!({ "fields": { "name": "Ada", "notes": "a" } }),
        serde_json::json!({ "fields": { "name": "Bob", "notes": "b" } }),
    ];
    let state = seeded_state(schema, &rows).await;
    let (forge, schema_def, policy_store, tenant_config, record_access_policy) =
        job_inputs(&state, "Subject").await;
    let job_actor = state.actor::<ExportJobActor>().expect("ExportJobActor").clone();

    let store = Arc::new(MockStore::default());
    let job_id = schema_forge_acton::export_job::new_job_id();
    let object_key = format!("exports/Subject/{job_id}.csv");
    let spec = ExportJobSpec {
        job_id: job_id.clone(),
        schema_name: "Subject".into(),
        schema_def,
        format: ExportFormat::Csv,
        filter: None,
        fields: None,
        max_rows: 1,
        bundle_files: false,
        claims: Some(make_claims(&["platform_admin"])),
        tenant_config,
        policy_store,
        record_access_policy,
        forge,
        store: store.clone(),
        object_key: object_key.clone(),
        audit_logger: None,
        subject: None,
    };

    job_actor.send(StartExportJob::new(spec)).await;
    let record = poll_until_terminal(&job_actor, &job_id).await;

    assert_eq!(record.status, ExportJobStatus::Failed);
    assert!(record.error.unwrap().contains("cap"));
    assert!(store.objects.lock().unwrap().is_empty(), "failed job must not upload");
}

// ---------------------------------------------------------------------------
// Tests — HTTP surface
// ---------------------------------------------------------------------------

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn async_request_without_storage_is_unavailable() {
    // No storage backend is configured in the test harness, so an async export
    // has nowhere to land and is refused with 503 rather than accepted.
    let rows = [serde_json::json!({ "fields": { "name": "Ada", "notes": "n" } })];
    let state = seeded_state(export_schema(), &rows).await;
    let app = app_with_claims(state, make_claims(&["platform_admin"]));

    let (status, json) = raw_request(
        &app,
        Method::POST,
        "/schemas/Subject/entities/export",
        Some(serde_json::json!({ "format": "csv", "async": true })),
    )
    .await;

    assert_eq!(status, StatusCode::SERVICE_UNAVAILABLE, "body: {json}");
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn xlsx_request_takes_async_path_not_deferred() {
    // A schema that declares `xlsx` in its formats. With no storage configured
    // the route still takes the async path and fails on missing storage (503),
    // proving xlsx is an accepted async format — NOT a 422 "deferred" rejection,
    // and NOT a 403 format-not-allowed.
    let schema = SchemaDefinition::new(
        SchemaId::new(),
        SchemaName::new("Sheet").unwrap(),
        vec![exportable_field("name")],
        vec![
            Annotation::Access {
                read: vec!["analyst".to_string()],
                write: vec!["analyst".to_string()],
                delete: vec![],
                cross_tenant_read: vec![],
            },
            Annotation::Export {
                formats: vec![ExportFormat::Xlsx],
                bundle_files: false,
                max_rows: 100,
            },
        ],
    )
    .unwrap();
    let rows = [serde_json::json!({ "fields": { "name": "Ada" } })];
    let state = seeded_state(schema, &rows).await;
    let app = app_with_claims(state, make_claims(&["platform_admin"]));

    let (status, json) = raw_request(
        &app,
        Method::POST,
        "/schemas/Sheet/entities/export",
        Some(serde_json::json!({ "format": "xlsx" })),
    )
    .await;

    // Storage is absent in the harness, so the async path is unavailable (503);
    // the key assertion is that we did NOT get 422 (deferred) or 403 (format not
    // allowed), i.e. xlsx is routed to the async pipeline.
    assert_eq!(status, StatusCode::SERVICE_UNAVAILABLE, "body: {json}");
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn status_for_unknown_job_is_not_found() {
    let rows = [serde_json::json!({ "fields": { "name": "Ada", "notes": "n" } })];
    let state = seeded_state(export_schema(), &rows).await;
    let app = app_with_claims(state, make_claims(&["platform_admin"]));

    let (status, json) = raw_request(
        &app,
        Method::GET,
        "/schemas/Subject/exports/exp_does_not_exist",
        None,
    )
    .await;

    assert_eq!(status, StatusCode::NOT_FOUND, "body: {json}");
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn status_on_non_export_schema_is_forbidden() {
    // A schema with no @export must refuse status lookups, fail-closed, even
    // though the job id is unknown — the export gate runs before the lookup.
    let schema = SchemaDefinition::new(
        SchemaId::new(),
        SchemaName::new("Locked").unwrap(),
        vec![exportable_field("name")],
        vec![Annotation::Access {
            read: vec!["analyst".to_string()],
            write: vec!["analyst".to_string()],
            delete: vec![],
            cross_tenant_read: vec![],
        }],
    )
    .unwrap();
    let state = seeded_state(schema, &[]).await;
    let app = app_with_claims(state, make_claims(&["platform_admin"]));

    let (status, json) = raw_request(
        &app,
        Method::GET,
        "/schemas/Locked/exports/exp_anything",
        None,
    )
    .await;

    assert_eq!(status, StatusCode::FORBIDDEN, "body: {json}");
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn status_endpoint_returns_completed_job_with_download_url() {
    // Drive a job to completion through the actor with a mock store, register it
    // under a known id, then read it back through the HTTP status route.
    let rows = [serde_json::json!({ "fields": { "name": "Ada", "notes": "n" } })];
    let state = seeded_state(export_schema(), &rows).await;
    let (forge, schema_def, policy_store, tenant_config, record_access_policy) =
        job_inputs(&state, "Subject").await;
    let job_actor = state.actor::<ExportJobActor>().expect("ExportJobActor").clone();

    let store = Arc::new(MockStore::default());
    let job_id = schema_forge_acton::export_job::new_job_id();
    let object_key = format!("exports/Subject/{job_id}.ndjson");
    let spec = ExportJobSpec {
        job_id: job_id.clone(),
        schema_name: "Subject".into(),
        schema_def,
        format: ExportFormat::Ndjson,
        filter: None,
        fields: None,
        max_rows: 100,
        bundle_files: false,
        claims: Some(make_claims(&["platform_admin"])),
        tenant_config,
        policy_store,
        record_access_policy,
        forge,
        store,
        object_key,
        audit_logger: None,
        // Owner of the job must match the subject that later polls the status
        // endpoint — export artifacts are owner-scoped.
        subject: Some("user:test-user".into()),
    };
    job_actor.send(StartExportJob::new(spec)).await;
    let record = poll_until_terminal(&job_actor, &job_id).await;
    assert_eq!(record.status, ExportJobStatus::Complete);

    let app = app_with_claims(state, make_claims(&["platform_admin"]));
    let (status, json) = raw_request(
        &app,
        Method::GET,
        &format!("/schemas/Subject/exports/{job_id}"),
        None,
    )
    .await;

    assert_eq!(status, StatusCode::OK, "body: {json}");
    assert_eq!(json["status"], "complete");
    assert_eq!(json["job_id"], job_id);
    assert!(json["download_url"].as_str().unwrap().starts_with("https://mock.example/"));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn status_endpoint_denies_cross_subject_access() {
    // IDOR regression: a job owned by `user:test-user` must NOT be readable by a
    // different subject, even one that itself holds export access on the schema.
    // The status endpoint must answer 404 (not 403) so the job id's existence
    // does not leak, and must never hand back the artifact's download URL.
    let rows = [serde_json::json!({ "fields": { "name": "Ada", "notes": "n" } })];
    let state = seeded_state(export_schema(), &rows).await;
    let (forge, schema_def, policy_store, tenant_config, record_access_policy) =
        job_inputs(&state, "Subject").await;
    let job_actor = state.actor::<ExportJobActor>().expect("ExportJobActor").clone();

    let store = Arc::new(MockStore::default());
    let job_id = schema_forge_acton::export_job::new_job_id();
    let object_key = format!("exports/Subject/{job_id}.ndjson");
    let spec = ExportJobSpec {
        job_id: job_id.clone(),
        schema_name: "Subject".into(),
        schema_def,
        format: ExportFormat::Ndjson,
        filter: None,
        fields: None,
        max_rows: 100,
        bundle_files: false,
        claims: Some(make_claims(&["platform_admin"])),
        tenant_config,
        policy_store,
        record_access_policy,
        forge,
        store,
        object_key,
        audit_logger: None,
        subject: Some("user:test-user".into()),
    };
    job_actor.send(StartExportJob::new(spec)).await;
    let record = poll_until_terminal(&job_actor, &job_id).await;
    assert_eq!(record.status, ExportJobStatus::Complete);

    // A different authenticated subject with the same export-capable role.
    let app = app_with_claims(
        state,
        make_claims_with_sub("user:attacker", &["platform_admin"]),
    );
    let (status, json) = raw_request(
        &app,
        Method::GET,
        &format!("/schemas/Subject/exports/{job_id}"),
        None,
    )
    .await;

    assert_eq!(status, StatusCode::NOT_FOUND, "body: {json}");
    assert!(
        json.get("download_url").is_none(),
        "cross-subject read must not leak a download url"
    );
}

// ---------------------------------------------------------------------------
// Tests — ZIP bundle (item 8)
// ---------------------------------------------------------------------------

use schema_forge_backend::entity::Entity;
use schema_forge_backend::traits::EntityStore;
use schema_forge_core::types::{
    DynamicValue, EntityId, FileAccess, FileConstraints, FileStatus,
};
use std::collections::BTreeMap;

/// Read an in-memory ZIP archive into `(member_name, bytes)` pairs.
fn read_zip_members(bytes: &[u8]) -> Vec<(String, Vec<u8>)> {
    use std::io::Read;
    let mut archive =
        zip::ZipArchive::new(std::io::Cursor::new(bytes.to_vec())).expect("valid zip archive");
    let mut out = Vec::new();
    for i in 0..archive.len() {
        let mut member = archive.by_index(i).expect("member");
        let name = member.name().to_string();
        let mut buf = Vec::new();
        member.read_to_end(&mut buf).expect("read member");
        out.push((name, buf));
    }
    out
}

fn file_field(name: &str) -> FieldDefinition {
    FieldDefinition::with_annotations(
        FieldName::new(name).unwrap(),
        FieldType::File(FileConstraints {
            bucket: "documents".to_string(),
            max_size_bytes: 1_000_000,
            mime_allowlist: vec![],
            access: FileAccess::default(),
        }),
        vec![],
        vec![FieldAnnotation::Exportable { flatten: None }],
    )
}

/// `Doc`: `title` (exportable text) + `attachment` (exportable file field), with
/// `@export(formats: [zip], bundle_files: <flag>)`.
fn zip_schema(bundle_files: bool) -> SchemaDefinition {
    SchemaDefinition::new(
        SchemaId::new(),
        SchemaName::new("Doc").unwrap(),
        vec![exportable_field("title"), file_field("attachment")],
        vec![
            Annotation::Access {
                read: vec!["analyst".to_string()],
                write: vec!["analyst".to_string()],
                delete: vec![],
                cross_tenant_read: vec![],
            },
            Annotation::Export {
                formats: vec![ExportFormat::Zip],
                bundle_files,
                max_rows: 100,
            },
        ],
    )
    .unwrap()
}

/// Build state over a `Doc` table seeded by inserting entities directly through
/// the backend (so a `file` field can carry a ready `FileAttachment` without
/// going through the upload/confirm flow), returning the state and the backend.
async fn seeded_doc_state(
    schema: SchemaDefinition,
    entities: Vec<Entity>,
) -> AppState<SchemaForgeConfig> {
    let backend = Arc::new(
        SurrealBackend::connect_memory("test", "test")
            .await
            .expect("mem surreal"),
    );
    provision(&backend, &schema).await;
    for entity in &entities {
        backend.create(entity).await.expect("seed entity");
    }

    let mut registry = HashMap::new();
    registry.insert(schema.name.as_str().to_string(), schema.clone());
    build_state(backend, registry).await
}

/// Build an entity with a single `attachment` file field carrying an `Available`
/// attachment that points at `blob_key`.
fn doc_with_attachment(id: &str, title: &str, blob_key: &str) -> Entity {
    let mut fields: BTreeMap<String, DynamicValue> = BTreeMap::new();
    fields.insert("title".into(), DynamicValue::Text(title.into()));
    fields.insert(
        "attachment".into(),
        DynamicValue::Json(serde_json::json!({
            "key": blob_key,
            "size": 5,
            "mime": "text/plain",
            "status": FileStatus::Available.as_str(),
            "created_at": "2024-01-01T00:00:00Z",
        })),
    );
    Entity::with_id(EntityId::new(id), SchemaName::new("Doc").unwrap(), fields)
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn zip_bundle_without_file_blobs_holds_only_data_member() {
    // bundle_files = false: the archive carries just the rectangular data file,
    // never any file-field blob, even though the schema has a file field.
    let schema = zip_schema(false);
    let entities = vec![doc_with_attachment("d1", "First", "blobs/d1.txt")];
    let state = seeded_doc_state(schema, entities).await;
    let (forge, schema_def, policy_store, tenant_config, record_access_policy) =
        job_inputs(&state, "Doc").await;
    let job_actor = state.actor::<ExportJobActor>().expect("ExportJobActor").clone();

    let store = Arc::new(MockStore::default());
    // The blob exists in storage, but with bundle_files=false it must NOT be pulled.
    store.seed_object("blobs/d1.txt", b"BLOB!".to_vec(), "text/plain");

    let job_id = schema_forge_acton::export_job::new_job_id();
    let object_key = format!("exports/Doc/{job_id}.zip");
    let spec = ExportJobSpec {
        job_id: job_id.clone(),
        schema_name: "Doc".into(),
        schema_def,
        format: ExportFormat::Zip,
        filter: None,
        fields: None,
        max_rows: 100,
        bundle_files: false,
        claims: Some(make_claims(&["platform_admin"])),
        tenant_config,
        policy_store,
        record_access_policy,
        forge,
        store: store.clone(),
        object_key: object_key.clone(),
        audit_logger: None,
        subject: Some("user:test-user".into()),
    };
    job_actor.send(StartExportJob::new(spec)).await;
    let record = poll_until_terminal(&job_actor, &job_id).await;
    assert_eq!(record.status, ExportJobStatus::Complete, "error: {:?}", record.error);
    assert_eq!(record.row_count, Some(1));

    let bytes = {
        let objects = store.objects.lock().unwrap();
        let (bytes, ctype) = objects.get(&object_key).expect("artifact uploaded");
        assert_eq!(ctype, "application/zip");
        assert_eq!(&bytes[..2], b"PK", "not a zip container");
        bytes.clone()
    };
    let members = read_zip_members(&bytes);
    // Only the data member; no files/ blob. The data file still lists the
    // exportable `attachment` file column (its metadata, not the raw bytes).
    assert_eq!(members.len(), 1, "members: {:?}", members.iter().map(|(n, _)| n).collect::<Vec<_>>());
    assert_eq!(members[0].0, "Doc.csv");
    let csv = String::from_utf8(members[0].1.clone()).unwrap();
    assert_eq!(csv.lines().next().unwrap(), "title,attachment");
    assert!(csv.contains("First"));
    // With bundle_files=false the raw blob bytes must not appear in the archive.
    assert!(!members.iter().any(|(_, b)| b.windows(5).any(|w| w == b"BLOB!")));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn zip_bundle_with_file_blobs_embeds_available_blob() {
    // bundle_files = true: the archive carries the data file plus the raw blob of
    // each @exportable, Available file field, pulled from storage.
    let schema = zip_schema(true);
    let entities = vec![
        doc_with_attachment("d1", "First", "blobs/d1.txt"),
        doc_with_attachment("d2", "Second", "blobs/d2.txt"),
    ];
    let state = seeded_doc_state(schema, entities).await;
    let (forge, schema_def, policy_store, tenant_config, record_access_policy) =
        job_inputs(&state, "Doc").await;
    let job_actor = state.actor::<ExportJobActor>().expect("ExportJobActor").clone();

    let store = Arc::new(MockStore::default());
    store.seed_object("blobs/d1.txt", b"hello".to_vec(), "text/plain");
    store.seed_object("blobs/d2.txt", b"world".to_vec(), "text/plain");

    let job_id = schema_forge_acton::export_job::new_job_id();
    let object_key = format!("exports/Doc/{job_id}.zip");
    let spec = ExportJobSpec {
        job_id: job_id.clone(),
        schema_name: "Doc".into(),
        schema_def,
        format: ExportFormat::Zip,
        filter: None,
        fields: None,
        max_rows: 100,
        bundle_files: true,
        claims: Some(make_claims(&["platform_admin"])),
        tenant_config,
        policy_store,
        record_access_policy,
        forge,
        store: store.clone(),
        object_key: object_key.clone(),
        audit_logger: None,
        subject: Some("user:test-user".into()),
    };
    job_actor.send(StartExportJob::new(spec)).await;
    let record = poll_until_terminal(&job_actor, &job_id).await;
    assert_eq!(record.status, ExportJobStatus::Complete, "error: {:?}", record.error);
    assert_eq!(record.row_count, Some(2));

    let bytes = {
        let objects = store.objects.lock().unwrap();
        let (bytes, ctype) = objects.get(&object_key).expect("artifact uploaded");
        assert_eq!(ctype, "application/zip");
        bytes.clone()
    };
    let members = read_zip_members(&bytes);
    let names: Vec<&str> = members.iter().map(|(n, _)| n.as_str()).collect();
    assert!(names.contains(&"Doc.csv"), "names: {names:?}");
    // Each row's blob lands under files/<field>/<entity_id>/<filename>. The entity
    // id is backend-generated (random TypeID), so assert on the structural prefix
    // and the deterministic filename segment rather than a literal id.
    let d1 = members
        .iter()
        .find(|(n, _)| n.starts_with("files/attachment/") && n.ends_with("/d1.txt"))
        .expect("d1 blob member");
    assert_eq!(d1.1, b"hello");
    let d2 = members
        .iter()
        .find(|(n, _)| n.starts_with("files/attachment/") && n.ends_with("/d2.txt"))
        .expect("d2 blob member");
    assert_eq!(d2.1, b"world");
    // Data file + two blobs.
    assert_eq!(members.len(), 3, "names: {names:?}");
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn zip_bundle_skips_non_available_blob() {
    // A quarantined (not Available) attachment is never embedded in the archive,
    // even with bundle_files = true.
    let schema = zip_schema(true);
    let mut fields: BTreeMap<String, DynamicValue> = BTreeMap::new();
    fields.insert("title".into(), DynamicValue::Text("Risky".into()));
    fields.insert(
        "attachment".into(),
        DynamicValue::Json(serde_json::json!({
            "key": "blobs/quarantined.txt",
            "size": 3,
            "mime": "text/plain",
            "status": FileStatus::Quarantined.as_str(),
            "created_at": "2024-01-01T00:00:00Z",
        })),
    );
    let entity = Entity::with_id(EntityId::new("q1"), SchemaName::new("Doc").unwrap(), fields);
    let state = seeded_doc_state(schema, vec![entity]).await;
    let (forge, schema_def, policy_store, tenant_config, record_access_policy) =
        job_inputs(&state, "Doc").await;
    let job_actor = state.actor::<ExportJobActor>().expect("ExportJobActor").clone();

    let store = Arc::new(MockStore::default());
    // Even though the bytes exist, a quarantined attachment must not be bundled.
    store.seed_object("blobs/quarantined.txt", b"BAD".to_vec(), "text/plain");

    let job_id = schema_forge_acton::export_job::new_job_id();
    let object_key = format!("exports/Doc/{job_id}.zip");
    let spec = ExportJobSpec {
        job_id: job_id.clone(),
        schema_name: "Doc".into(),
        schema_def,
        format: ExportFormat::Zip,
        filter: None,
        fields: None,
        max_rows: 100,
        bundle_files: true,
        claims: Some(make_claims(&["platform_admin"])),
        tenant_config,
        policy_store,
        record_access_policy,
        forge,
        store: store.clone(),
        object_key: object_key.clone(),
        audit_logger: None,
        subject: Some("user:test-user".into()),
    };
    job_actor.send(StartExportJob::new(spec)).await;
    let record = poll_until_terminal(&job_actor, &job_id).await;
    assert_eq!(record.status, ExportJobStatus::Complete, "error: {:?}", record.error);

    let bytes = {
        let objects = store.objects.lock().unwrap();
        objects.get(&object_key).expect("artifact uploaded").0.clone()
    };
    let members = read_zip_members(&bytes);
    // Only the data file; the quarantined blob is excluded.
    assert_eq!(members.len(), 1);
    assert_eq!(members[0].0, "Doc.csv");
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn zip_request_takes_async_path_not_deferred() {
    // A schema declaring `zip` must route to the async pipeline. With no storage
    // configured the route fails on missing storage (503) — NOT a 422 "deferred"
    // (zip is now supported) and NOT a 403 format-not-allowed.
    let schema = zip_schema(true);
    let state = seeded_doc_state(schema, vec![]).await;
    let app = app_with_claims(state, make_claims(&["platform_admin"]));

    let (status, json) = raw_request(
        &app,
        Method::POST,
        "/schemas/Doc/entities/export",
        Some(serde_json::json!({ "format": "zip" })),
    )
    .await;

    assert_eq!(status, StatusCode::SERVICE_UNAVAILABLE, "body: {json}");
}
