[package]
name = "schema-forge-postgres"
version = "0.17.0"
edition = "2021"

[dependencies]
schema-forge-core = { path = "../schema-forge-core" }
schema-forge-backend = { path = "../schema-forge-backend" }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
arc-swap = "1.9.1"
tokio = { version = "1", features = ["macros"] }
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio", "tls-rustls-aws-lc-rs", "postgres", "json", "chrono", "uuid"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }
