//! CEL conformance oracle (#90).
//!
//! Runs the engine against the vendored `google/cel-spec` `simple` corpus,
//! filtered to the SchemaForge-relevant subset (proto-message sections are
//! excluded by design — see [`EXCLUDED`]). Reports pass/fail by feature and
//! enforces a ratcheting baseline: each engine stage (#107/#108/#109) raises
//! [`MIN_PASS_BASELINE`] as it turns sections green.
//!
//! The corpus is pre-encoded to binary by `build.rs`; this harness only decodes
//! and runs it. Generated protobuf types are confined to the `proto` module
//! below and never touch the engine's public API.

#[allow(clippy::all, clippy::pedantic, clippy::nursery, dead_code, unused)]
mod proto {
    // Machine-generated by prost-build (build.rs); not hand-editable, so pedantic
    // lints are scoped out of it here rather than suppressed in engine logic.
    include!(concat!(env!("OUT_DIR"), "/_includes.rs"));
}

use std::collections::BTreeMap;

use prost::Message;
use schema_forge_cel::{evaluate, Bindings, CelError, CelKey, CelValue};

use proto::cel::expr::conformance::test::{simple_test::ResultMatcher, SimpleTestFile};
use proto::cel::expr::{expr_value::Kind as ExprValueKind, value::Kind as ValueKind, Value};

/// Feature files vendored and graded (the SchemaForge-relevant subset).
const INCLUDED: &[&str] = &[
    "basic",
    "comparisons",
    "logic",
    "string",
    "integer_math",
    "fp_math",
    "lists",
    "macros",
    "macros2",
    "timestamps",
    "conversions",
    "optionals",
    "string_ext",
    "math_ext",
    "encoders_ext",
    "namespace",
    "parse",
    "plumbing",
];

/// Feature files deliberately excluded: they test protobuf-message semantics
/// (our value domain is `DynamicValue`, not proto messages). Recorded, not
/// silently dropped.
const EXCLUDED: &[&str] = &[
    "wrappers",
    "proto2",
    "proto2_ext",
    "proto3",
    "fields",
    "enums",
    "dynamic",
    "type_deduction",
    "unknowns",
    "bindings_ext",
    "block_ext",
    "network_ext",
];

/// Total passing tests the engine must currently meet. Ratcheted up per stage:
/// Stage 1 (harness only) = 0; #107 turns on `parse`/`plumbing`; #108 the core
/// sections; #109 the stdlib sections.
///
/// #108 (evaluator core) raised this to 815. #109 (standard library) raised it to
/// 1018. #114 (parsing `-9223372036854775808` as `i64::MIN`) raises it to 1037:
/// `integer_math` is now fully green (64/64), and the fix also lifts `basic`
/// (42/43) and `comparisons` (330/406). Remaining reds across the subset are
/// proto-message constructs (out of scope), namespace-qualified type names, and
/// the `dyn` unknown-variable message spelling — none are engine bugs.
const MIN_PASS_BASELINE: usize = 1037;

#[derive(Default)]
struct Tally {
    pass: usize,
    fail: usize,
    skipped: usize,
}

impl Tally {
    fn total(&self) -> usize {
        self.pass + self.fail + self.skipped
    }
}

#[test]
fn conformance_subset() {
    let dir = env!("CEL_CONFORMANCE_BINPB");
    let mut files: Vec<std::path::PathBuf> = std::fs::read_dir(dir)
        .expect("conformance binpb dir (set by build.rs)")
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("binpb"))
        .collect();
    files.sort();

    assert!(
        !files.is_empty(),
        "no conformance binpb files found in {dir} — build.rs pre-encode step failed"
    );

    let mut by_feature: BTreeMap<String, Tally> = BTreeMap::new();

    for path in &files {
        let feature = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("utf8 binpb stem")
            .to_string();

        assert!(
            INCLUDED.contains(&feature.as_str()),
            "vendored feature '{feature}' is not classified in INCLUDED — \
             classify it or move it to EXCLUDED (no silent coverage gaps)"
        );

        let bytes = std::fs::read(path).expect("read binpb");
        let file = SimpleTestFile::decode(&bytes[..]).expect("decode SimpleTestFile");
        let tally = by_feature.entry(feature).or_default();

        for section in &file.section {
            for test in &section.test {
                run_test(test, tally);
            }
        }
    }

    report(&by_feature);

    let total_pass: usize = by_feature.values().map(|t| t.pass).sum();
    let total: usize = by_feature.values().map(Tally::total).sum();
    assert!(total > 0, "harness decoded zero tests");
    // Ratchet floor: fail if passing count drops below the committed baseline.
    // Expressed via `cmp` so it stays a real check as the baseline rises past 0.
    assert!(
        total_pass.cmp(&MIN_PASS_BASELINE) != std::cmp::Ordering::Less,
        "conformance regressed: {total_pass} passing < baseline {MIN_PASS_BASELINE}"
    );
}

fn run_test(test: &proto::cel::expr::conformance::test::SimpleTest, tally: &mut Tally) {
    // Build bindings; bail to "skipped" if any binding isn't a plain value we model.
    let mut bindings = Bindings::new();
    for (name, ev) in &test.bindings {
        match &ev.kind {
            Some(ExprValueKind::Value(v)) => match convert_value(v) {
                Some(cv) => {
                    bindings.insert(name.clone(), cv);
                }
                None => {
                    tally.skipped += 1;
                    return;
                }
            },
            _ => {
                tally.skipped += 1;
                return;
            }
        }
    }

    match &test.result_matcher {
        Some(ResultMatcher::Value(v)) => match convert_value(v) {
            Some(expected) => match evaluate(&test.expr, &bindings) {
                Ok(actual) if actual == expected => tally.pass += 1,
                _ => tally.fail += 1,
            },
            // Expected value is something we don't model (e.g. proto Any) — out of scope.
            None => tally.skipped += 1,
        },
        Some(ResultMatcher::EvalError(set)) => {
            let expected: Vec<&str> = set.errors.iter().map(|s| s.message.as_str()).collect();
            match evaluate(&test.expr, &bindings) {
                Err(CelError::Eval(e)) if msg_matches(e.message(), &expected) => tally.pass += 1,
                _ => tally.fail += 1,
            }
        }
        Some(ResultMatcher::AnyEvalErrors(_)) => match evaluate(&test.expr, &bindings) {
            Err(CelError::Eval(_)) => tally.pass += 1,
            _ => tally.fail += 1,
        },
        // typed_result / unknown matchers are out of scope for this harness.
        _ => tally.skipped += 1,
    }
}

/// Lenient error-message match: the spec error set lists acceptable messages.
///
/// The corpus spells some equivalent errors two ways — `no_such_overload` vs
/// `no such overload`, `division by zero` vs `divide by zero`. The engine emits
/// one canonical spelling; to reclaim those correct-but-differently-spelled
/// errors we normalize separators on BOTH sides before the substring test:
/// lowercase, treat `_` as a space, and collapse runs of whitespace. This affects
/// ONLY eval-error message matching (value results stay type-exact in `run_test`),
/// so it cannot mask a wrong value. It is deliberately limited to separator
/// normalization and does not broaden matching to unrelated messages.
fn msg_matches(actual: &str, expected: &[&str]) -> bool {
    let na = normalize_msg(actual);
    expected.iter().any(|e| {
        let ne = normalize_msg(e);
        ne == na || na.contains(&ne) || ne.contains(&na)
    })
}

/// Normalize a CEL error message for separator-insensitive comparison.
fn normalize_msg(s: &str) -> String {
    s.to_lowercase()
        .replace('_', " ")
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
}

/// Convert a `cel.expr.Value` into our `CelValue`. Returns `None` for shapes we
/// do not model (proto `Any`, or nested unsupported values).
fn convert_value(v: &Value) -> Option<CelValue> {
    match v.kind.as_ref()? {
        ValueKind::NullValue(_) => Some(CelValue::Null),
        ValueKind::BoolValue(b) => Some(CelValue::Bool(*b)),
        ValueKind::Int64Value(i) => Some(CelValue::Int(*i)),
        ValueKind::Uint64Value(u) => Some(CelValue::Uint(*u)),
        ValueKind::DoubleValue(d) => Some(CelValue::Double(*d)),
        ValueKind::StringValue(s) => Some(CelValue::String(s.clone())),
        ValueKind::BytesValue(b) => Some(CelValue::Bytes(b.clone())),
        ValueKind::EnumValue(e) => Some(CelValue::Int(i64::from(e.value))),
        ValueKind::TypeValue(t) => Some(CelValue::Type(t.clone())),
        ValueKind::ListValue(l) => {
            let mut out = Vec::with_capacity(l.values.len());
            for item in &l.values {
                out.push(convert_value(item)?);
            }
            Some(CelValue::List(out))
        }
        ValueKind::MapValue(m) => {
            let mut out = BTreeMap::new();
            for entry in &m.entries {
                let key = value_to_key(entry.key.as_ref()?)?;
                let val = convert_value(entry.value.as_ref()?)?;
                out.insert(key, val);
            }
            Some(CelValue::Map(out))
        }
        ValueKind::ObjectValue(_) => None,
    }
}

/// Convert a `cel.expr.Value` into a legal CEL map key.
fn value_to_key(v: &Value) -> Option<CelKey> {
    match v.kind.as_ref()? {
        ValueKind::BoolValue(b) => Some(CelKey::Bool(*b)),
        ValueKind::Int64Value(i) => Some(CelKey::Int(*i)),
        ValueKind::Uint64Value(u) => Some(CelKey::Uint(*u)),
        ValueKind::StringValue(s) => Some(CelKey::String(s.clone())),
        _ => None,
    }
}

fn report(by_feature: &BTreeMap<String, Tally>) {
    eprintln!("\n=== CEL conformance (SchemaForge subset) ===");
    let (mut tp, mut tf, mut ts) = (0usize, 0usize, 0usize);
    for (feature, t) in by_feature {
        eprintln!(
            "  {feature:<14} pass {:>4}  fail {:>4}  skip {:>4}  / {}",
            t.pass,
            t.fail,
            t.skipped,
            t.total()
        );
        tp += t.pass;
        tf += t.fail;
        ts += t.skipped;
    }
    eprintln!("  {:-<54}", "");
    eprintln!(
        "  {:<14} pass {tp:>4}  fail {tf:>4}  skip {ts:>4}  / {}",
        "TOTAL",
        tp + tf + ts
    );
    eprintln!(
        "  excluded (proto-message, out of scope): {}",
        EXCLUDED.join(", ")
    );
    eprintln!("  baseline: {MIN_PASS_BASELINE} passing required\n");
}
