//! End-to-end signing tests at the CLI surface.
//!
//! These exercise the `schemaforge sign` → `schemaforge verify` →
//! `schemaforge parse` round trip the way an operator actually runs
//! them. Anything covered at the library level (in
//! `schema-forge-signing` unit tests) is *not* re-tested here — these
//! tests target the CLI wiring: argument parsing, config plumbing,
//! exit codes, and the actual on-disk file layout.

use assert_cmd::Command;
use predicates::prelude::*;
use std::fs;
use tempfile::TempDir;

#[allow(deprecated)]
fn schema_forge() -> Command {
    Command::cargo_bin("schemaforge").unwrap()
}

/// Writes a minimal but real schema layout and a `config.toml` whose
/// `[schema_forge.signing]` section trusts the key generated by
/// `schemaforge sign --ed25519-generate`. Returns the project root.
fn scaffold_project(mode: &str) -> TempDir {
    let dir = TempDir::new().unwrap();
    let schemas = dir.path().join("schemas");
    fs::create_dir_all(&schemas).unwrap();
    fs::write(
        schemas.join("user.schema"),
        "schema User { name: text required }\n",
    )
    .unwrap();
    fs::write(
        schemas.join("doc.schema"),
        "schema Doc { title: text required }\n",
    )
    .unwrap();

    // Config has no signing section yet; sign step will print the
    // public key and the caller will splice it in.
    let config = format!(
        "[surrealdb]\nurl = \"mem://\"\nnamespace = \"t\"\ndatabase = \"t\"\n\n\
         [schema_forge.signing]\nmode = \"{mode}\"\n"
    );
    fs::write(dir.path().join("config.toml"), config).unwrap();
    dir
}

/// Run `schemaforge sign --ed25519-generate <key> --print-pubkey` on
/// the project's schemas dir; return the SPKI public-key base64 the
/// command emitted so we can splice it into the trust policy.
fn sign_with_generated_key(project: &std::path::Path) -> String {
    let key_path = project.join("keys/sign.pem");
    let schemas = project.join("schemas");
    let out = schema_forge()
        .args([
            "sign",
            schemas.to_str().unwrap(),
            "--ed25519-generate",
            key_path.to_str().unwrap(),
            "--print-pubkey",
        ])
        .assert()
        .success()
        .get_output()
        .stderr
        .clone();

    let text = String::from_utf8(out).unwrap();
    // The status line is "public key (base64 SPKI): <b64>".
    let line = text
        .lines()
        .find(|l| l.contains("public key (base64 SPKI):"))
        .expect("pubkey line in sign output");
    line.split_once(": ")
        .map(|(_, v)| v.trim().to_string())
        .expect("pubkey value")
}

fn append_trust_anchor(project: &std::path::Path, pubkey_b64: &str) {
    let cfg_path = project.join("config.toml");
    let mut cfg = fs::read_to_string(&cfg_path).unwrap();
    cfg.push_str(&format!(
        "\n[[schema_forge.signing.trusted_signers]]\n\
         kind = \"ed25519\"\nname = \"test-key\"\npublic_key_b64 = \"{pubkey_b64}\"\n"
    ));
    fs::write(cfg_path, cfg).unwrap();
}

#[test]
fn sign_then_verify_then_parse_round_trip() {
    let project = scaffold_project("enforce");
    let pubkey = sign_with_generated_key(project.path());
    append_trust_anchor(project.path(), &pubkey);

    // Manifest + signatures must exist on disk.
    let schemas = project.path().join("schemas");
    assert!(schemas.join("schemas.manifest.toml").exists());
    assert!(schemas.join("schemas.manifest.toml.sig").exists());
    assert!(schemas.join("user.schema.sig").exists());
    assert!(schemas.join("doc.schema.sig").exists());

    // verify
    schema_forge()
        .current_dir(project.path())
        .args(["verify", "schemas"])
        .assert()
        .success();

    // parse — same trust policy, but now flow through the parser too
    schema_forge()
        .current_dir(project.path())
        .args(["parse", "schemas"])
        .assert()
        .success();
}

#[test]
fn parse_fails_under_enforce_when_a_schema_is_tampered() {
    let project = scaffold_project("enforce");
    let pubkey = sign_with_generated_key(project.path());
    append_trust_anchor(project.path(), &pubkey);

    // Tamper with one schema after signing.
    let user = project.path().join("schemas/user.schema");
    fs::write(&user, "schema User { name: text }\n# evil change\n").unwrap();

    schema_forge()
        .current_dir(project.path())
        .args(["parse", "schemas"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("verification failed").or(
            predicate::str::contains("hash mismatch").or(predicate::str::contains(
                "schemas/user.schema",
            )),
        ));
}

#[test]
fn parse_fails_under_enforce_when_extra_schema_appears() {
    let project = scaffold_project("enforce");
    let pubkey = sign_with_generated_key(project.path());
    append_trust_anchor(project.path(), &pubkey);

    fs::write(
        project.path().join("schemas/rogue.schema"),
        "schema Rogue { x: text }\n",
    )
    .unwrap();

    schema_forge()
        .current_dir(project.path())
        .args(["parse", "schemas"])
        .assert()
        .failure();
}

#[test]
fn parse_warns_but_succeeds_under_warn_mode() {
    let project = scaffold_project("warn");
    let pubkey = sign_with_generated_key(project.path());
    append_trust_anchor(project.path(), &pubkey);

    // Tamper with the bytes (changes the hash) but keep the result valid DSL
    // so the parse step itself doesn't fail. Adding a trailing newline is
    // enough to make the hash diverge from the manifest's pin — that's the
    // condition warn mode is supposed to log-but-continue on.
    let user = project.path().join("schemas/user.schema");
    let original = fs::read_to_string(&user).unwrap();
    fs::write(&user, format!("{original}\n")).unwrap();

    schema_forge()
        .current_dir(project.path())
        .args(["parse", "schemas"])
        .assert()
        .success()
        .stderr(predicate::str::contains("schema signature warning"));
}

#[test]
fn parse_under_off_mode_does_not_verify() {
    let project = scaffold_project("off");

    // No sign call — no manifest, no signatures. Off mode skips them.
    schema_forge()
        .current_dir(project.path())
        .args(["parse", "schemas"])
        .assert()
        .success();
}

#[test]
fn no_verify_flag_refused_under_enforce_without_env_override() {
    let project = scaffold_project("enforce");
    let pubkey = sign_with_generated_key(project.path());
    append_trust_anchor(project.path(), &pubkey);

    schema_forge()
        .current_dir(project.path())
        .env_remove("SCHEMAFORGE_ALLOW_NO_VERIFY")
        .args(["--no-verify", "parse", "schemas"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("--no-verify refused"));
}

#[test]
fn no_verify_flag_honoured_with_env_override() {
    let project = scaffold_project("enforce");
    let pubkey = sign_with_generated_key(project.path());
    append_trust_anchor(project.path(), &pubkey);

    schema_forge()
        .current_dir(project.path())
        .env("SCHEMAFORGE_ALLOW_NO_VERIFY", "1")
        .args(["--no-verify", "parse", "schemas"])
        .assert()
        .success();
}

#[test]
fn verify_command_requires_active_mode() {
    let project = scaffold_project("off");
    schema_forge()
        .current_dir(project.path())
        .args(["verify", "schemas"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("warn").or(predicate::str::contains("enforce")));
}

#[test]
fn sign_help_lists_the_three_schemes() {
    let out = schema_forge()
        .args(["sign", "--help"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let text = String::from_utf8(out).unwrap();
    assert!(text.contains("--ed25519-key"));
    assert!(text.contains("--ed25519-generate"));
    assert!(text.contains("--ssh-key"));
    assert!(text.contains("--keyless"));
}

// ---------------------------------------------------------------------------
// SSH allowed_signers (Phase 2) coverage. Each test below stands up a real
// ed25519 OpenSSH key on disk, signs with it via `schemaforge sign --ssh-key`,
// builds an allowed_signers trust file, and exercises verify/parse paths.
// ---------------------------------------------------------------------------

use ssh_key::private::Ed25519Keypair;
use ssh_key::{LineEnding, PrivateKey};

/// Write an OpenSSH-format private key to `<project>/keys/operator` and
/// return the matching public-key line so a caller can build the
/// allowed_signers file. Comment defaults to a recognisable principal.
fn write_test_ssh_key(project: &std::path::Path, principal: &str) -> (std::path::PathBuf, String) {
    let kp = Ed25519Keypair::from_seed(&[0x55; 32]);
    let pk = PrivateKey::new(kp.into(), principal).unwrap();
    let key_path = project.join("keys/operator");
    fs::create_dir_all(key_path.parent().unwrap()).unwrap();
    pk.write_openssh_file(&key_path, LineEnding::LF).unwrap();
    let pubkey = pk.public_key().to_openssh().unwrap();
    (key_path, pubkey)
}

fn write_allowed_signers(project: &std::path::Path, line: &str) -> std::path::PathBuf {
    let path = project.join("trust/allowed_signers");
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(&path, format!("{line}\n")).unwrap();
    path
}

fn append_ssh_trust_anchor(project: &std::path::Path, allowed_signers_path: &std::path::Path) {
    let cfg_path = project.join("config.toml");
    let mut cfg = fs::read_to_string(&cfg_path).unwrap();
    cfg.push_str(&format!(
        "\n[[schema_forge.signing.trusted_signers]]\n\
         kind = \"ssh-allowed-signers\"\nname = \"ops-allowed-signers\"\npath = {:?}\n",
        allowed_signers_path.display().to_string()
    ));
    fs::write(cfg_path, cfg).unwrap();
}

#[test]
fn ssh_sign_then_verify_then_parse_round_trip() {
    let project = scaffold_project("enforce");
    let (key_path, pubkey_line) = write_test_ssh_key(project.path(), "roland@govcraft.ai");
    let allowed = write_allowed_signers(
        project.path(),
        &format!("roland@govcraft.ai {pubkey_line}"),
    );
    append_ssh_trust_anchor(project.path(), &allowed);

    let schemas = project.path().join("schemas");
    schema_forge()
        .current_dir(project.path())
        .args([
            "sign",
            schemas.to_str().unwrap(),
            "--ssh-key",
            key_path.to_str().unwrap(),
        ])
        .assert()
        .success();

    // Per-file PEM-armored SSHSIG was written.
    let sig_bytes = fs::read(schemas.join("user.schema.sig")).unwrap();
    let sig_text = String::from_utf8(sig_bytes).unwrap();
    assert!(sig_text.starts_with("-----BEGIN SSH SIGNATURE-----"));

    schema_forge()
        .current_dir(project.path())
        .args(["verify", "schemas"])
        .assert()
        .success();

    schema_forge()
        .current_dir(project.path())
        .args(["parse", "schemas"])
        .assert()
        .success();
}

#[test]
fn ssh_verify_rejects_tampered_schema_under_enforce() {
    let project = scaffold_project("enforce");
    let (key_path, pubkey_line) = write_test_ssh_key(project.path(), "roland@govcraft.ai");
    let allowed = write_allowed_signers(
        project.path(),
        &format!("roland@govcraft.ai {pubkey_line}"),
    );
    append_ssh_trust_anchor(project.path(), &allowed);

    let schemas = project.path().join("schemas");
    schema_forge()
        .current_dir(project.path())
        .args([
            "sign",
            schemas.to_str().unwrap(),
            "--ssh-key",
            key_path.to_str().unwrap(),
        ])
        .assert()
        .success();

    // Flip a byte after signing.
    let user = schemas.join("user.schema");
    let orig = fs::read_to_string(&user).unwrap();
    fs::write(&user, format!("{orig}\n# tamper\n")).unwrap();

    schema_forge()
        .current_dir(project.path())
        .args(["verify", "schemas"])
        .assert()
        .failure();
}

#[test]
fn ssh_verify_rejects_unknown_signer() {
    let project = scaffold_project("enforce");
    // Sign with one key …
    let (signing_key, _signing_pubkey) =
        write_test_ssh_key(project.path(), "roland@govcraft.ai");
    // … but trust a *different* key.
    let other_kp = Ed25519Keypair::from_seed(&[0x99; 32]);
    let other_pk = PrivateKey::new(other_kp.into(), "ops@govcraft.ai").unwrap();
    let other_pubkey = other_pk.public_key().to_openssh().unwrap();
    let allowed = write_allowed_signers(
        project.path(),
        &format!("ops@govcraft.ai {other_pubkey}"),
    );
    append_ssh_trust_anchor(project.path(), &allowed);

    let schemas = project.path().join("schemas");
    schema_forge()
        .current_dir(project.path())
        .args([
            "sign",
            schemas.to_str().unwrap(),
            "--ssh-key",
            signing_key.to_str().unwrap(),
        ])
        .assert()
        .success();

    schema_forge()
        .current_dir(project.path())
        .args(["verify", "schemas"])
        .assert()
        .failure();
}

#[test]
fn ssh_sign_print_pubkey_emits_allowed_signers_hint() {
    let project = scaffold_project("off");
    let (key_path, _) = write_test_ssh_key(project.path(), "roland@govcraft.ai");
    let schemas = project.path().join("schemas");
    let out = schema_forge()
        .current_dir(project.path())
        .args([
            "sign",
            schemas.to_str().unwrap(),
            "--ssh-key",
            key_path.to_str().unwrap(),
            "--print-pubkey",
            "--ssh-principal",
            "audit-bot@govcraft.ai",
        ])
        .assert()
        .success()
        .get_output()
        .stderr
        .clone();
    let text = String::from_utf8(out).unwrap();
    assert!(text.contains("allowed_signers line"));
    assert!(text.contains("audit-bot@govcraft.ai"));
    assert!(text.contains("ssh-allowed-signers"));
}

#[test]
fn ssh_verify_with_namespace_restriction_matches_schemaforge() {
    let project = scaffold_project("enforce");
    let (key_path, pubkey_line) = write_test_ssh_key(project.path(), "roland@govcraft.ai");
    // Explicit namespaces= entry whitelisting the schemaforge namespace.
    let allowed = write_allowed_signers(
        project.path(),
        &format!(
            "roland@govcraft.ai namespaces=\"schema-forge-signing@govcraft.ai\" {pubkey_line}"
        ),
    );
    append_ssh_trust_anchor(project.path(), &allowed);

    let schemas = project.path().join("schemas");
    schema_forge()
        .current_dir(project.path())
        .args([
            "sign",
            schemas.to_str().unwrap(),
            "--ssh-key",
            key_path.to_str().unwrap(),
        ])
        .assert()
        .success();

    schema_forge()
        .current_dir(project.path())
        .args(["verify", "schemas"])
        .assert()
        .success();
}

#[test]
fn ssh_verify_rejects_when_namespace_not_allowed() {
    let project = scaffold_project("enforce");
    let (key_path, pubkey_line) = write_test_ssh_key(project.path(), "roland@govcraft.ai");
    // Namespaces= restricts to *some other* namespace; schemaforge sig
    // is in `schema-forge-signing@govcraft.ai`, so this entry must not match.
    let allowed = write_allowed_signers(
        project.path(),
        &format!(
            "roland@govcraft.ai namespaces=\"file@openssh.com\" {pubkey_line}"
        ),
    );
    append_ssh_trust_anchor(project.path(), &allowed);

    let schemas = project.path().join("schemas");
    schema_forge()
        .current_dir(project.path())
        .args([
            "sign",
            schemas.to_str().unwrap(),
            "--ssh-key",
            key_path.to_str().unwrap(),
        ])
        .assert()
        .success();

    schema_forge()
        .current_dir(project.path())
        .args(["verify", "schemas"])
        .assert()
        .failure();
}

#[test]
fn ssh_verify_rejects_expired_entry() {
    let project = scaffold_project("enforce");
    let (key_path, pubkey_line) = write_test_ssh_key(project.path(), "roland@govcraft.ai");
    // valid-before in the past — entry has expired, must not accept.
    let allowed = write_allowed_signers(
        project.path(),
        &format!(
            "roland@govcraft.ai valid-before=\"19991231\" {pubkey_line}"
        ),
    );
    append_ssh_trust_anchor(project.path(), &allowed);

    let schemas = project.path().join("schemas");
    schema_forge()
        .current_dir(project.path())
        .args([
            "sign",
            schemas.to_str().unwrap(),
            "--ssh-key",
            key_path.to_str().unwrap(),
        ])
        .assert()
        .success();

    schema_forge()
        .current_dir(project.path())
        .args(["verify", "schemas"])
        .assert()
        .failure();
}
