//! `@generated` marker header handling.
//!
//! Every file the codegen subsystem *owns* (not *preserves*) carries a
//! marker header on its first non-empty line. The header is a single-line
//! comment in the file's native comment syntax that contains the literal
//! substring `@generated by schema-forge`. Presence of the marker is the
//! contract: on regeneration we read the existing file, verify the marker,
//! then overwrite silently. Absence of the marker is fatal — it means a
//! human has taken ownership of the file, and we refuse to clobber their
//! work.

use std::path::Path;

use super::error::CodegenError;

/// Comment syntax for a file format. Picked by file extension.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CommentStyle {
    /// `// ...` — Rust, proto, JS, TS, C family.
    DoubleSlash,
    /// `# ...` — TOML, shell, YAML, Python.
    Hash,
    /// `<!-- ... -->` — HTML, Markdown.
    HtmlComment,
}

impl CommentStyle {
    /// Pick a style based on the path's file extension. Unknown extensions
    /// fall back to `#`, which is the most universally tolerated line
    /// comment syntax in config-ish files.
    pub fn for_path(path: &Path) -> Self {
        match path.extension().and_then(|e| e.to_str()) {
            Some("rs" | "proto" | "js" | "ts" | "tsx" | "jsx" | "c" | "cpp" | "h" | "css") => {
                Self::DoubleSlash
            }
            Some("toml" | "sh" | "yml" | "yaml" | "py") => Self::Hash,
            Some("md" | "html" | "htm") => Self::HtmlComment,
            _ => Self::Hash,
        }
    }

    /// Render the marker header line for this style.
    pub fn header_line(self, generator: &str) -> String {
        let body = format!("@generated by schema-forge {generator} — DO NOT EDIT");
        match self {
            Self::DoubleSlash => format!("// {body}"),
            Self::Hash => format!("# {body}"),
            Self::HtmlComment => format!("<!-- {body} -->"),
        }
    }

    /// Strip comment punctuation from a single line and return the inner
    /// text, or `None` if the line does not match this style's comment
    /// syntax. The inner text is trimmed of leading/trailing whitespace.
    pub fn strip(self, line: &str) -> Option<&str> {
        let trimmed = line.trim();
        match self {
            Self::DoubleSlash => trimmed.strip_prefix("//").map(str::trim),
            Self::Hash => trimmed.strip_prefix('#').map(str::trim),
            Self::HtmlComment => trimmed
                .strip_prefix("<!--")
                .and_then(|s| s.strip_suffix("-->"))
                .map(str::trim),
        }
    }
}

/// Marker helper tied to a specific generator name (e.g. `"hooks"`).
#[derive(Debug, Clone, Copy)]
pub struct Marker {
    /// Generator identifier embedded in every header line.
    pub generator: &'static str,
}

impl Marker {
    /// Create a marker bound to the given generator name.
    pub const fn new(generator: &'static str) -> Self {
        Self { generator }
    }

    /// Prepend the marker header to `contents`, choosing comment style from
    /// the path extension. Returns a new `String` with the header and a
    /// trailing newline before the original contents.
    pub fn prepend(&self, path: &Path, contents: &str) -> String {
        let style = CommentStyle::for_path(path);
        let header = style.header_line(self.generator);
        if contents.is_empty() {
            format!("{header}\n")
        } else {
            format!("{header}\n{contents}")
        }
    }

    /// Verify that `contents` carries a `@generated by schema-forge` marker
    /// on its first non-empty line (under the comment style matching
    /// `path`). Returns [`CodegenError::MarkerMissing`] if absent.
    pub fn verify(&self, path: &Path, contents: &str) -> Result<(), CodegenError> {
        let style = CommentStyle::for_path(path);
        let first = contents.lines().find(|l| !l.trim().is_empty());
        let inner = first
            .and_then(|l| style.strip(l))
            .ok_or_else(|| CodegenError::MarkerMissing {
                path: path.to_path_buf(),
            })?;
        if inner.contains("@generated by schema-forge") {
            Ok(())
        } else {
            Err(CodegenError::MarkerMissing {
                path: path.to_path_buf(),
            })
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn p(s: &str) -> PathBuf {
        PathBuf::from(s)
    }

    #[test]
    fn comment_style_for_rs() {
        assert_eq!(CommentStyle::for_path(&p("a.rs")), CommentStyle::DoubleSlash);
    }

    #[test]
    fn comment_style_for_toml() {
        assert_eq!(CommentStyle::for_path(&p("Cargo.toml")), CommentStyle::Hash);
    }

    #[test]
    fn comment_style_for_md() {
        assert_eq!(
            CommentStyle::for_path(&p("x.md")),
            CommentStyle::HtmlComment
        );
    }

    #[test]
    fn comment_style_for_proto() {
        assert_eq!(
            CommentStyle::for_path(&p("x.proto")),
            CommentStyle::DoubleSlash
        );
    }

    #[test]
    fn comment_style_unknown_falls_back_to_hash() {
        assert_eq!(CommentStyle::for_path(&p("noext")), CommentStyle::Hash);
    }

    #[test]
    fn header_line_double_slash_format() {
        let line = CommentStyle::DoubleSlash.header_line("hooks");
        assert_eq!(line, "// @generated by schema-forge hooks — DO NOT EDIT");
    }

    #[test]
    fn header_line_hash_format() {
        let line = CommentStyle::Hash.header_line("site");
        assert_eq!(line, "# @generated by schema-forge site — DO NOT EDIT");
    }

    #[test]
    fn header_line_html_format() {
        let line = CommentStyle::HtmlComment.header_line("hooks");
        assert_eq!(
            line,
            "<!-- @generated by schema-forge hooks — DO NOT EDIT -->"
        );
    }

    #[test]
    fn strip_double_slash() {
        assert_eq!(CommentStyle::DoubleSlash.strip("// hi"), Some("hi"));
    }

    #[test]
    fn strip_hash() {
        assert_eq!(CommentStyle::Hash.strip("#  hi "), Some("hi"));
    }

    #[test]
    fn strip_html() {
        assert_eq!(
            CommentStyle::HtmlComment.strip("<!-- hi -->"),
            Some("hi")
        );
    }

    #[test]
    fn strip_returns_none_on_mismatch() {
        assert_eq!(CommentStyle::DoubleSlash.strip("hi"), None);
    }

    #[test]
    fn prepend_adds_header_to_nonempty() {
        let m = Marker::new("hooks");
        let out = m.prepend(&p("x.rs"), "fn main() {}\n");
        assert!(out.starts_with("// @generated by schema-forge hooks"));
        assert!(out.contains("fn main()"));
    }

    #[test]
    fn prepend_handles_empty_contents() {
        let m = Marker::new("hooks");
        let out = m.prepend(&p("x.toml"), "");
        assert_eq!(out, "# @generated by schema-forge hooks — DO NOT EDIT\n");
    }

    #[test]
    fn verify_accepts_valid_marker_rs() {
        let m = Marker::new("hooks");
        let src = "// @generated by schema-forge hooks — DO NOT EDIT\nfn x() {}\n";
        m.verify(&p("x.rs"), src).unwrap();
    }

    #[test]
    fn verify_accepts_valid_marker_toml() {
        let m = Marker::new("hooks");
        let src = "# @generated by schema-forge hooks — DO NOT EDIT\n[package]\n";
        m.verify(&p("Cargo.toml"), src).unwrap();
    }

    #[test]
    fn verify_rejects_missing_marker() {
        let m = Marker::new("hooks");
        let err = m.verify(&p("x.rs"), "fn main() {}\n").unwrap_err();
        assert!(matches!(err, CodegenError::MarkerMissing { .. }));
    }

    #[test]
    fn verify_rejects_empty_file() {
        let m = Marker::new("hooks");
        let err = m.verify(&p("x.rs"), "").unwrap_err();
        assert!(matches!(err, CodegenError::MarkerMissing { .. }));
    }

    #[test]
    fn verify_tolerates_leading_blank_line() {
        let m = Marker::new("hooks");
        let src = "\n// @generated by schema-forge hooks — DO NOT EDIT\nfn x() {}\n";
        m.verify(&p("x.rs"), src).unwrap();
    }

    #[test]
    fn verify_accepts_cross_generator_marker() {
        // Tolerant: a hooks marker in a site file still verifies as
        // schemaforge-owned. The manifest/sentinel catches the wrong tool.
        let m = Marker::new("site");
        let src = "// @generated by schema-forge hooks — DO NOT EDIT\nfn x() {}\n";
        m.verify(&p("x.rs"), src).unwrap();
    }
}
