//! Shared primitives for file-emitting codegen subcommands.
//!
//! This module extracts the bits that every generator needs — manifest,
//! marker header, sentinel, plan-based write + check — so that
//! `hooks generate`, `site generate`, and any future generator behave
//! identically and by construction.
//!
//! # Overview
//!
//! A generator builds a flat [`Vec<FilePlan>`][write::FilePlan] describing
//! every file it wants to produce. Each entry carries a [`WriteMode`]:
//!
//! - [`WriteMode::Owned`] — the generator owns the file, always rewrites
//!   it, and tracks it in [`Manifest`] so orphans can be pruned. Must
//!   carry a `@generated by schema-forge` marker on re-read.
//! - [`WriteMode::Preserve`] — scaffolded once, then left alone. Not
//!   tracked. Rewritten only with `force_user_files`.
//!
//! The generator then calls [`write::write_plan`] (real write) or
//! [`write::check_plan`] (dry-run drift report). Both functions handle
//! marker verification, manifest diffing / pruning, sentinel enforcement,
//! and empty-parent-directory tidying on their own.
//!
//! See `commands/hooks.rs` for a full worked example.

pub mod error;
pub mod manifest;
pub mod marker;
pub mod sentinel;
pub mod write;

pub use sentinel::SentinelKind;
pub use write::{check_plan, write_plan, FilePlan, WriteMode, WriteOptions};
